import {StyleSheet, Dimensions} from 'react-native';

const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;
const CARD_WIDTH = width * 0.7; // Adjust for two cards per screen
const CARD_HEIGHT = 160;

export const styles = StyleSheet.create({
  
  container: {
    backgroundColor: '#fff7ea',
    padding: 0,
  },
  topbar_title: {
    color: 'white',
  },
  topbar_input:{
    minWidth:"55%",
    maxWidth:"55%"
  }
  ,
  safeareabar: {
    top: 0,
    height: 25,
    width: '100%',
    backgroundColor: 'grey',
  },
  topbar: {
    backgroundColor: '#ffbc00',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 5,
  },
  header: {
    // flex: 1,
    flexDirection: 'row',
    backgroundColor: '#f9f7f9',
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    maxHeight: 60,
    height: '100%',
  },
  menu_ico: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 3,
    width: '50%',
    maxHeight: 120,
  },
  menu_ico_bar: {
    maxWidth: 45,
    backgroundColor: '#f08c1f',
    maxHeight: 8,
    height: '10%',
    width: '90%',
    margin: 2,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  bar1: {
    width: '90%',
  },
  bar2: {
    width: '75%',
  },
  bar3: {
    width: '50%',
  },
  logo_container: {
    height: '100%',
    flex: 7,
    paddingHorizontal: 5,
  },

  logo: {
    width: '100%',
    height: '100%',
  },
  flowerbar: {
    flex: 7,
    overflow: 'hidden',
    height: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  flowerbar_ico: {
    resizeMode: 'contain',
    height: 100,
    width: '100%',
  },
  pressed: {
    opacity: 0.6,
  },
  search_ico: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  search_ico_img: {
    resizeMode: 'contain',
    height: '80%',
    width: '70%',
    zIndex: 99,
    // borderWidth: 2,
    // borderColor: "black",
  },
  title: {
    fontWeight: 400,
    fontSize: 15,

    color: 'black',
    fontFamily: 'Fredoka-SemiBold',
    marginVertical: 1,
    paddingVertical: 10,
  },
  background: {
    resizeMode: 'contain', // or 'contain', 'stretch'
    height: '100%',
    paddingHorizontal: 10,
  },
  home_section: {
    maxWidth: '100%',
    maxHeight: '45%',
    overflow: 'hidden',
    // borderWidth: 6,
    // borderColor: "green",
  },
  top_heading: {
    marginTop: 20,
    marginVertical: 10,
    color: 'white',
    fontSize: 25,
    maxWidth: '70%',
    fontFamily: 'Fredoka-SemiBold',
    // borderWidth: 4,
    // borderColor: "green",
  },
  verified_img: {
    // position: "absolute",
    // resizeMode: 'stretch', // or 'contain', 'stretch'
    marginTop: -15,
    left: -6,
    maxWidth: '75%',
    maxHeight: 80,
    // borderWidth: 2,
    // borderColor: "red",
  },
  glow_heading: {
    marginTop: -30,
    marginHorizontal: 10,
    color: 'white',
    fontSize: 40,
    fontFamily: 'Fredoka-Bold',
    fontWeight: 500,
    textShadowColor: 'rgba(255, 255, 255, 0.8)', // Glow effect
    textShadowOffset: {width: 0, height: 0},
    textShadowRadius: 30, // Adjust for a stronger glow
    // borderWidth: 4,
    // borderColor: "purple",
  },
  vrindavan_img: {
    resizeMode: 'contain',
    marginVertical: 5,
    maxHeight: 100,
    maxWidth: '90%',
    // borderWidth: 4,
    // borderColor: "green",
  },
  section: {
    margin: 10,
    maxHeight: height * 0.35,
    // borderWidth: 2,
    // borderColor: 'green',
  },
  section_heading: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    // borderWidth: 4,
    // borderColor: 'green',
  },
  heading_text: {
    margin: 4,
    color: '#ffbc00',
    fontSize: 30,
    fontFamily: 'bernoru-blackultraexpanded',
    fontWeight: 'bold',
  },
  swastik: {
    marginTop: 5,
    resizeMode: 'contain',
    marginHorizontal: 5,
    height: 40,
    width: 40,
    // borderWidth: 4,
    // borderColor: 'green',
  },
  heading_underline: {
    marginBottom: 10,
    resizeMode: 'cover',
    maxWidth: '60%',
    maxHeight: 10,
    // borderWidth: 4,
    // borderColor: "yellow",
  },
  sideBar: {
    position: 'absolute',
    left: 0,
    zIndex: 4,
    paddingLeft: 4,
    overflow: 'hidden',
    paddingRight: 4,
    top: 25,
    minWidth: '70%',
    maxWidth: '71%',
    backgroundColor: 'white',
    minHeight: height * 0.9,
    // paddingTop:-10,
    borderTopEndRadius: 60,
    borderBottomEndRadius: 150,
  },
  bar11: {
    height: 6,
    width: '70%',
  },
  sideBarServices: {
    minWidth: '80%',
    marginTop: 15,
    minHeight: '2.4%',
    marginLeft: -25,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  blurEffect: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    backfaceVisibility: 'hidden', // Works only on web
    zIndex: 9,
  },
  puja_slider: {
    borderWidth: 4,
    borderColor: 'red',
  },
  listContainer: {
    paddingHorizontal: 5,
  },
  categoryContainer: {},
  card: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    backgroundColor: '#fff',
    borderRadius: 15,
    overflow: 'hidden',
    marginHorizontal: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    position: 'relative',
    paddingBottom: 0,
  },
  catCard: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT * 3,
    marginHorizontal: 10,
    paddingBottom: 0,
    position: 'relative',
    borderColor: 'black',
    overflow: 'hidden',
    backgroundColor: '#fff',
    borderRadius: 10,

    // iOS Shadow
    shadowColor: 'blue',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 10,
    fontSize: 16,
    fontWeight: 'bold',
  },
  catCard_image: {
    // width:'100%',
    height: '90%',
    backgroundColor: '#ffffff',
  },
  container_cat: {
    flex: 1,
    position: 'absolute',
    top: 350,
    left: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#001F3F', // Dark Blue Background
    borderRadius: 67,
    opacity: 0.7,
  },
  glassBox: {
    width: 90,
    height: 90,
    backgroundColor: 'rgba(0,0,0, 0.4)', // Light Transparent Blue
    borderRadius: 67,
    alignItems: 'center',
    justifyContent: 'center',
    // White Border for Glassy Effect
  },
  text: {
    color: 'white',
    fontSize: 30,
    fontWeight: 600,
  },
  image: {
    width: '100%',
    height: '100%', // Reduced height to fit text
    resizeMode: 'cover',
  },
  card_image: {
    height: CARD_HEIGHT * 0.7,
    // borderWidth: 3,
  },
  bottomRow: {
    // flex: 3, // Takes available space
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    maxHeight: CARD_HEIGHT * 0.3,
    marginBottom: 0,
    // borderWidth: 3,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '55%',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    zIndex: -1,
  },
  specialTag: {
    position: 'absolute',
    marginTop: 15,
    fontSize: 12,
    fontWeight: 'bold',
    color: 'white',
    backgroundColor: '#aa53d1',
    padding: 5,
    paddingLeft: 20,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  // title: {
  //   fontSize: 15,
  //   fontWeight: 'bold',
  //   color: '#555555',
  //   fontFamily: 'Fredoka-SemiBold',
  //   marginVertical: 1,
  //   paddingVertical: 10,
  // },
  bookNow: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'white',
    // fontFamily: 'Fredoka_Condensed-Bold',
    fontFamily: 'Fredoka-SemiBold',
  },
  bookNowContainer: {
    alignContent: 'center',
    justifyContent: 'center',
    marginVertical:"auto",
    paddingVertical: 2,
    maxWidth:"40%",
    paddingHorizontal: 10,
    backgroundColor: '#ffbc00',
    borderRadius: 20,
    height: '80%',
    marginLeft: 10,
    marginRight: 0,
    flex: 1,
    // borderWidth: 2,
  },
  input: {
    height: "80%",
    // margin: 10,
    padding: 15,
    backgroundColor: 'white',
    borderWidth: 0.5,
    borderRightWidth:0,
    borderColor: 'grey',
    color: 'grey',
    borderRadius: 5,
    fontFamily: 'Fredoka-Regular',
    fontSize: 19,
  },

  signupForm: {
    // borderWidth: 2,
    padding: '5%',
    justifyContent: 'center',
  },
  emailInput: {
    // borderWidth: 5,
    // borderColor: "red",
    width: '95%',
  },
  countryCode: {
    width: '20%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  phoneNum: {
    // width: '70%',
    marginHorizontal: 5,
    flex: 1
  },
  signup_title: {
    fontSize: 30,
    fontFamily: 'Fredoka-Regular',
    padding: 5,
  },
});

// export const styles = StyleSheet.create({
//   container: {
//     backgroundColor: '#fff7ea',
//     padding: 0,
//   },
//   topbar_title: {
//     color: 'white',
//   },
//   safeareabar: {
//     top: 0,
//     height: 25,
//     width: '100%',
//     backgroundColor: 'grey',
//   },
//   topbar: {
//     backgroundColor: '#ffbc00',
//     flexDirection: 'row',
//     justifyContent: 'space-between',
//     padding: 5,
//   },
//   header: {
//     // flex: 1,
//     flexDirection: 'row',
//     backgroundColor: '#f9f7f9',
//     paddingHorizontal: 5,
//     alignItems: 'center',
//     justifyContent: 'center',
//     maxHeight: 60,
//     height: '100%',
//   },
//   menu_ico: {
//     flex: 2,
//     alignItems: 'center',
//     justifyContent: 'center',
//     padding: 3,
//     width: '50%',
//     maxHeight: 120,
//   },
//   menu_ico_bar: {
//     maxWidth: 45,
//     backgroundColor: '#f08c1f',
//     maxHeight: 8,
//     height: '10%',
//     width: '90%',
//     margin: 2,
//     borderRadius: 20,
//     alignSelf: 'flex-start',
//   },
//   bar1: {
//     width: '90%',
//   },
//   bar2: {
//     width: '75%',
//   },
//   bar3: {
//     width: '50%',
//   },
//   logo_container: {
//     height: '100%',
//     flex: 7,
//     paddingHorizontal: 5,
//   },
//   logo: {
//     width: '100%',
//     height: '100%',
//   },
//   flowerbar: {
//     flex: 7,
//     overflow: 'hidden',
//     height: '90%',
//     alignItems: 'center',
//     justifyContent: 'center',
//     paddingHorizontal: 2,
//   },
//   flowerbar_ico: {
//     resizeMode: 'contain',
//     height: 100,
//     width: '100%',
//   },
//   search_ico: {
//     flex: 2,
//     alignItems: 'center',
//     justifyContent: 'center',
//   },
//   search_ico_img: {
//     resizeMode: 'contain',
//     height: '80%',
//     width: '70%',
//     zIndex: 99,
//     // borderWidth: 2,
//     // borderColor: "black",
//   },
//   title: {
//     color: 'white',
//     fontWeight: 400,
//   },
//   background: {
//     resizeMode: 'contain', // or 'contain', 'stretch'
//     height: '100%',
//     paddingHorizontal: 10,
//   },
//   home_section: {
//     maxWidth: '100%',
//     maxHeight: '45%',
//     overflow: 'hidden',
//     // borderWidth: 6,
//     // borderColor: "green",
//   },
//   top_heading: {
//     marginTop: 20,
//     marginVertical: 10,
//     color: 'white',
//     fontSize: 25,
//     maxWidth: '70%',
//     fontFamily: 'Fredoka-SemiBold',
//     // borderWidth: 4,
//     // borderColor: "green",
//   },
//   verified_img: {
//     // position: "absolute",
//     // resizeMode: 'stretch', // or 'contain', 'stretch'
//     marginTop: -15,
//     left: -6,
//     maxWidth: '75%',
//     maxHeight: 80,
//     // borderWidth: 2,
//     // borderColor: "red",
//   },
//   glow_heading: {
//     marginTop: -30,
//     marginHorizontal: 10,
//     color: 'white',
//     fontSize: 40,
//     fontFamily: 'Fredoka-Bold',
//     fontWeight: 500,
//     textShadowColor: 'rgba(255, 255, 255, 0.8)', // Glow effect
//     textShadowOffset: {width: 0, height: 0},
//     textShadowRadius: 30, // Adjust for a stronger glow
//     // borderWidth: 4,
//     // borderColor: "purple",
//   },
//   vrindavan_img: {
//     resizeMode: 'contain',
//     marginVertical: 5,
//     maxHeight: 100,
//     maxWidth: '90%',
//     // borderWidth: 4,
//     // borderColor: "green",
//   },
//   section: {
//     margin: 10,
//     maxHeight: height*0.35,
//     // borderWidth: 2,
//     // borderColor: 'green',
//   },
//   section_heading: {
//     flexDirection: 'row',
//     justifyContent: 'flex-start',
//     // borderWidth: 4,
//     // borderColor: 'green',
//   },
//   heading_text: {
//     margin: 4,
//     color: '#ffbc00',
//     fontSize: 30,
//     fontFamily: 'bernoru-blackultraexpanded',
//     fontWeight: 'bold',
//   },
//   swastik: {
//     marginTop: 5,
//     resizeMode: 'contain',
//     marginHorizontal: 5,
//     height: 40,
//     width: 40,
//     // borderWidth: 4,
//     // borderColor: 'green',
//   },
//   heading_underline: {
//     marginBottom: 10,
//     resizeMode: 'cover',
//     maxWidth: '60%',
//     maxHeight: 10,
//     // borderWidth: 4,
//     // borderColor: "yellow",
//   },
//   puja_slider: {
//     borderWidth: 4,
//     borderColor: 'red',
//   },
//   listContainer: {
//     paddingHorizontal: 5,
//   },
//   card: {
//     width: CARD_WIDTH,
//     height: CARD_HEIGHT,
//     backgroundColor: '#fff',
//     borderRadius: 15,
//     overflow: 'hidden',
//     marginHorizontal: 10,
//     elevation: 5,
//     shadowColor: '#000',
//     shadowOffset: {width: 0, height: 3},
//     shadowOpacity: 0.2,
//     shadowRadius: 4,
//     position: 'relative',
//     overflow: 'hidden',
//     paddingBottom: 0,
//   },
//   image: {
//     width: '100%',
//     height: '100%', // Reduced height to fit text
//     resizeMode: 'cover',
//   },
//   card_image: {
//     height: CARD_HEIGHT * 0.7,
//     // borderWidth: 3,
//   },
//   bottomRow: {
//     // flex: 3, // Takes available space
//     flexDirection: 'row',
//     justifyContent: 'space-between',
//     alignItems: 'center',
//     paddingHorizontal: 10,
//     maxHeight: CARD_HEIGHT * 0.3,
//     paddingHorizontal: 10,
//     marginBottom: 0,
//     // borderWidth: 3,
//   },
//   overlay: {
//     position: 'absolute',
//     top: 0,
//     left: 0,
//     width: '100%',
//     height: '55%',
//     backgroundColor: 'rgba(0, 0, 0, 0.3)',
//     zIndex: -1,
//   },
//   specialTag: {
//     position: 'absolute',
//     marginTop: 15,
//     fontSize: 12,
//     fontWeight: 'bold',
//     color: 'white',
//     backgroundColor: '#aa53d1',
//     padding: 5,
//     paddingLeft: 20,
//     borderTopRightRadius: 20,
//     borderBottomRightRadius: 20,
//   },
//   title: {
//     fontSize: 15,
//     fontWeight: 'bold',
//     color: '#555555',
//     fontFamily: 'Fredoka-SemiBold',
//     marginVertical: 1,
//     paddingVertical: 10,
//   },
//   bookNow: {
//     fontSize: 15,
//     fontWeight: 'bold',
//     color: 'white',
//     // fontFamily: 'Fredoka_Condensed-Bold',
//     fontFamily: 'Fredoka-SemiBold',
//   },
//   bookNowContainer: {
//     alignContent: 'center',
//     justifyContent: 'center',
//     // padding: 6,
//     paddingHorizontal: 10,
//     backgroundColor: '#ffbc00',
//     borderRadius: 20,
//     height: '80%',
//     marginLeft: 10,
//     marginRight: 0,
//     flex: 1,
//     // borderWidth: 2,
//   },
// });
